# Generated by Django 6.1.1 on 2026-09-14 19:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=120)),
                ('source_action_id', models.CharField(max_length=240)),
                ('action_type', models.CharField(choices=[('cash_dividend', 'Cash dividend'), ('stock_split', 'Stock split'), ('spinoff', 'Spinoff'), ('rights_issue', 'Rights issue')], max_length=24)),
                ('announced_at', models.DateTimeField(blank=True, null=True)),
                ('ex_date', models.DateField()),
                ('ratio', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('cash_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corporate_actions', to='companies.security')),
            ],
            options={
                'ordering': ['ex_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PriceObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=120)),
                ('observed_at', models.DateTimeField()),
                ('trading_date', models.DateField()),
                ('currency_code', models.CharField(max_length=3)),
                ('price_units', models.CharField(default='currency/share', max_length=24)),
                ('volume_units', models.CharField(default='shares', max_length=24)),
                ('open', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('close', models.DecimalField(decimal_places=8, max_digits=24)),
                ('adjusted_close', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('adjustment_status', models.CharField(choices=[('unadjusted', 'Unadjusted'), ('split_adjusted', 'Split adjusted'), ('fully_adjusted', 'Fully adjusted')], default='unadjusted', max_length=24)),
                ('retrieved_at', models.DateTimeField()),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_observations', to='companies.security')),
            ],
            options={
                'ordering': ['security', 'observed_at', 'source', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PriceCorporateAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate_action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_links', to='market_data.corporateaction')),
                ('price_observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_links', to='market_data.priceobservation')),
            ],
        ),
        migrations.AddConstraint(
            model_name='corporateaction',
            constraint=models.UniqueConstraint(fields=('source', 'source_action_id'), name='unique_corporate_action_source_id'),
        ),
        migrations.AddConstraint(
            model_name='priceobservation',
            constraint=models.UniqueConstraint(fields=('security', 'observed_at', 'source'), name='unique_price_observation_source'),
        ),
        migrations.AddConstraint(
            model_name='pricecorporateaction',
            constraint=models.UniqueConstraint(fields=('price_observation', 'corporate_action'), name='unique_price_corporate_action_link'),
        ),
    ]
