# Generated by Django 6.1.1 on 2026-09-14 19:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilingMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=120)),
                ('source_document_id', models.CharField(max_length=240)),
                ('retrieved_at', models.DateTimeField()),
                ('effective_date', models.DateField()),
                ('units', models.CharField(max_length=32)),
                ('form_type', models.CharField(max_length=32)),
                ('document_url', models.URLField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filings', to='companies.company')),
                ('security', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filings', to='companies.security')),
            ],
        ),
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('annual', 'Annual'), ('quarterly', 'Quarterly'), ('ttm', 'Trailing twelve months')], max_length=16)),
                ('fiscal_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fiscal_period', models.CharField(max_length=8)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reporting_periods', to='companies.company')),
                ('security', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reporting_periods', to='companies.security')),
            ],
            options={
                'ordering': ['-period_end', '-id'],
            },
        ),
        migrations.AddField(
            model_name='filingmetadata',
            name='reporting_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filings', to='financials.reportingperiod'),
        ),
        migrations.CreateModel(
            name='IncomeStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=120)),
                ('retrieved_at', models.DateTimeField()),
                ('effective_date', models.DateField()),
                ('units', models.CharField(max_length=32)),
                ('data_quality', models.CharField(choices=[('missing', 'Missing'), ('valid', 'Valid'), ('suspect', 'Suspect')], default='valid', max_length=16)),
                ('revenue', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('operating_income', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('net_income', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.company')),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financials.filingmetadata')),
                ('security', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.security')),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financials.reportingperiod')),
            ],
        ),
        migrations.CreateModel(
            name='CashFlowStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=120)),
                ('retrieved_at', models.DateTimeField()),
                ('effective_date', models.DateField()),
                ('units', models.CharField(max_length=32)),
                ('data_quality', models.CharField(choices=[('missing', 'Missing'), ('valid', 'Valid'), ('suspect', 'Suspect')], default='valid', max_length=16)),
                ('operating_cash_flow', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('investing_cash_flow', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('financing_cash_flow', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.company')),
                ('security', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.security')),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financials.filingmetadata')),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financials.reportingperiod')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=120)),
                ('retrieved_at', models.DateTimeField()),
                ('effective_date', models.DateField()),
                ('units', models.CharField(max_length=32)),
                ('data_quality', models.CharField(choices=[('missing', 'Missing'), ('valid', 'Valid'), ('suspect', 'Suspect')], default='valid', max_length=16)),
                ('total_assets', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('total_liabilities', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('shareholders_equity', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.company')),
                ('security', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.security')),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financials.filingmetadata')),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financials.reportingperiod')),
            ],
        ),
        migrations.AddConstraint(
            model_name='filingmetadata',
            constraint=models.UniqueConstraint(fields=('source', 'source_document_id'), name='unique_filing_source_document'),
        ),
        migrations.AddConstraint(
            model_name='reportingperiod',
            constraint=models.UniqueConstraint(fields=('company', 'security', 'period_type', 'fiscal_year', 'fiscal_period'), name='unique_reporting_period_identity'),
        ),
        migrations.AddConstraint(
            model_name='reportingperiod',
            constraint=models.CheckConstraint(condition=models.Q(('period_start__lte', models.F('period_end'))), name='reporting_period_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='incomestatement',
            constraint=models.UniqueConstraint(fields=('company', 'security', 'reporting_period', 'source'), name='unique_income_statement_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='cashflowstatement',
            constraint=models.UniqueConstraint(fields=('company', 'security', 'reporting_period', 'source'), name='unique_cash_flow_statement_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='balancesheet',
            constraint=models.UniqueConstraint(fields=('company', 'security', 'reporting_period', 'source'), name='unique_balance_sheet_snapshot'),
        ),
    ]
