# Generated by Django 6.1.1 on 2026-09-14 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_peergroupproposal_peergroupmember'),
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('default_units', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ForecastPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('label', models.CharField(max_length=32)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_periods', to='companies.company')),
                ('security', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forecast_periods', to='companies.security')),
            ],
            options={
                'ordering': ['period_end', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('management', 'Management guidance'), ('consensus', 'Analyst consensus'), ('internal', 'Internal model')], max_length=16)),
                ('value', models.DecimalField(blank=True, decimal_places=8, max_digits=28, null=True)),
                ('units', models.CharField(max_length=32)),
                ('retrieved_at', models.DateTimeField(blank=True, null=True)),
                ('effective_date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecasts', to='companies.company')),
                ('security', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forecasts', to='companies.security')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecasts', to='financials.forecastmeasure')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecasts', to='financials.forecastperiod')),
            ],
            options={
                'ordering': ['period__period_end', 'measure__code', 'source'],
            },
        ),
        migrations.AddConstraint(
            model_name='forecastperiod',
            constraint=models.UniqueConstraint(fields=('company', 'security', 'period_start', 'period_end'), name='unique_forecast_period'),
        ),
        migrations.AddConstraint(
            model_name='forecastperiod',
            constraint=models.CheckConstraint(condition=models.Q(('period_start__lte', models.F('period_end'))), name='forecast_period_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='companyforecast',
            constraint=models.UniqueConstraint(fields=('company', 'security', 'measure', 'period', 'source', 'effective_date'), name='unique_company_forecast_snapshot'),
        ),
    ]
