# Generated by Django 6.1.1 on 2026-09-14 00:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('name', models.CharField(max_length=120, unique=True)),
                ('country_code', models.CharField(default='US', max_length=2)),
                ('mic', models.CharField(blank=True, max_length=4, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='industries', to='companies.sector')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=240, unique=True)),
                ('common_name', models.CharField(max_length=240)),
                ('cik', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('country_code', models.CharField(default='US', max_length=2)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='companies.industry')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='companies.sector')),
            ],
            options={
                'ordering': ['common_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_identifier', models.CharField(max_length=64, unique=True)),
                ('security_type', models.CharField(choices=[('common_stock', 'Common stock'), ('preferred_stock', 'Preferred stock'), ('adr', 'American depositary receipt'), ('etf', 'Exchange-traded fund')], default='common_stock', max_length=24)),
                ('share_class', models.CharField(default='', max_length=16)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='securities', to='companies.company')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='securities', to='companies.exchange')),
            ],
            options={
                'ordering': ['security_identifier'],
            },
        ),
        migrations.CreateModel(
            name='TickerIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(1)])),
                ('is_primary', models.BooleanField(default=False)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticker_identifiers', to='companies.exchange')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticker_identifiers', to='companies.security')),
            ],
            options={
                'ordering': ['exchange', 'symbol'],
            },
        ),
        migrations.AddConstraint(
            model_name='industry',
            constraint=models.UniqueConstraint(fields=('sector', 'name'), name='unique_industry_per_sector'),
        ),
        migrations.AddConstraint(
            model_name='security',
            constraint=models.UniqueConstraint(fields=('company', 'exchange', 'security_type', 'share_class'), name='unique_company_exchange_security_class'),
        ),
        migrations.AddConstraint(
            model_name='tickeridentifier',
            constraint=models.UniqueConstraint(fields=('exchange', 'symbol'), name='unique_ticker_per_exchange'),
        ),
    ]
