# Generated by Django 6.1.1 on 2026-09-14 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerGroupProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='fixture', max_length=120)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('minimum_candidates', models.PositiveSmallIntegerField(default=5)),
                ('eligible_count', models.PositiveIntegerField(default=0)),
                ('sufficient_universe', models.BooleanField(default=False)),
                ('explanation', models.TextField()),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('confirmed', 'Confirmed')], default='proposed', max_length=16)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='peer_group_proposal', to='companies.company')),
            ],
            options={
                'ordering': ['company__common_name'],
            },
        ),
        migrations.CreateModel(
            name='PeerGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('score', models.FloatField(default=0)),
                ('confidence', models.FloatField(default=0)),
                ('reasons', models.JSONField(default=list)),
                ('component_scores', models.JSONField(default=dict)),
                ('selected', models.BooleanField(default=True)),
                ('origin', models.CharField(choices=[('algorithm', 'Algorithmic proposal'), ('user_added', 'User added'), ('user_removed', 'User removed')], default='algorithm', max_length=16)),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='peer_group_memberships', to='companies.company')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='companies.peergroupproposal')),
            ],
            options={
                'ordering': ['rank', 'peer__common_name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('proposal', 'peer'), name='unique_peer_group_member')],
            },
        ),
    ]
